jobs:
  label-when-reviewed:
    name: Label PRs when reviewed
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Do nothing. Only trigger corresponding workflow_run event
      run: echo
name: Label-when-reviewed
on:
  repository_dispatch:
    types: trigger-ga___approve-label-trigger.yml
