jobs:
  label-when-approved:
    name: Label when approved
    outputs:
      isApprovedByAnyone: ${{ steps.label-when-approved-by-anyone.outputs.isApproved
        }}
      isApprovedByCommitters: ${{ steps.label-when-approved-by-committers.outputs.isApproved
        }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout ${{ github.ref }} ( ${{ github.sha }} )
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        submodules: recursive
    - continue-on-error: true
      id: source-run-info
      name: Get information about the original trigger of the run
      uses: ./.github/actions/get-workflow-origin
      with:
        sourceRunId: ${{ github.event.workflow_run.id }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      id: label-when-approved-by-committers
      name: Label when approved by committers
      uses: ./.github/actions/label-when-approved-action
      with:
        label: approved
        pullRequestNumber: ${{ steps.source-run-info.outputs.pullRequestNumber }}
        remove_label_when_approval_missing: 'true'
        require_committers_approval: 'true'
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      id: label-when-approved-by-anyone
      name: Label when approved by anyone
      uses: ./.github/actions/label-when-approved-action
      with:
        label: reviewed
        pullRequestNumber: ${{ steps.source-run-info.outputs.pullRequestNumber }}
        remove_label_when_approval_missing: 'true'
        token: ${{ secrets.GITHUB_TOKEN }}
name: Label when approved workflow run
on:
  repository_dispatch:
    types: trigger-ga___approve-label.yml
permissions:
  checks: write
  contents: read
  pull-requests: write
