concurrency:
  cancel-in-progress: true
  group: backend-${{ github.event.pull_request.number || github.ref }}
jobs:
  build:
    if: github.repository =='DTStack/chunjun'
    name: Build the project.
    needs:
    - spotless-check
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: add dependencies
      run: 'wget http://nexus.dev.dtstack.cn/nexus/content/repositories/dtstack-release/com/esen/jdbc/gbase/8.3.81.53/gbase-8.3.81.53.jar

        ./mvnw install:install-file -DgroupId=com.esen.jdbc -DartifactId=gbase -Dversion=8.3.81.53
        -Dpackaging=jar -Dfile=./gbase-8.3.81.53.jar

        '
    - continue-on-error: true
      name: build project
      run: './mvnw clean package -Dmaven.test.skip --no-snapshot-updates

        '
    - continue-on-error: true
      name: unit-test
      run: './mvnw -T 1C clean compile test -DskipUT=false -DskipITCase=false --no-snapshot-updates

        '
    - continue-on-error: true
      env:
        MAVEN_OPTS: -Xmx2048m
      name: integration-test
      run: './mvnw -T 1C -B verify -DskipUT=true -DskipIT=false --no-snapshot-updates
        -pl chunjun-e2e -am

        '
    timeout-minutes: 90
  spotless-check:
    if: github.repository =='DTStack/chunjun'
    name: Check code style with spotless.
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: 8
    - continue-on-error: true
      name: Spotless Check
      run: './mvnw spotless:check

        '
    timeout-minutes: 10
name: Check Code.
on:
  repository_dispatch:
    types: trigger-ga___build.yml
